#
# System settings
#
DNS_IP="${DNS_IP:-208.67.222.222}"
SYSTEM_TIMEZONE="${SYSTEM_TIMEZONE:-EST}"
SYSTEM_LOCALE="${SYSTEM_LOCALE:-en_US.UTF-8}"

#
# Base package versions
#
BUILD_ESSENTIAL_VERSION="${BUILD_ESSENTIAL_VERSION:-11.6ubuntu6}"
CMAKE_VERSION="${CMAKE_VERSION:-2.8.12.2-0ubuntu3}"
RAKE_VERSION="${RAKE_VERSION:-10.0.4-1}"
UNZIP_VERSION="${UNZIP_VERSION:-6.0-9ubuntu1.5}"
CURL_VERSION="${CURL_VERSION:-7.35.0-1ubuntu2.5}"
ZLIBC_VERSION="${ZLIBC_VERSION:-0.9k-4.1}"
BISON_VERSION="${BISON_VERSION:-2:3.0.2.dfsg-2}"
LLVM_VERSION="${LLVM_VERSION:-1:3.4-0ubuntu1}"
LLVM_DEV_VERSION="${LLVM_DEV_VERSION:-1:3.4-0ubuntu1}"
ZLIB1G_DEV_VERSION="${ZLIB1G_DEV_VERSION:-1:1.2.8.dfsg-1ubuntu1}"
LIBPOPT_DEV_VERSION="${LIBPOPT_DEV_VERSION:-1.16-8ubuntu1}"
LIBSSL_DEV_VERSION="${LIBSSL_DEV_VERSION:-1.0.1f-1ubuntu2.16}"
LIBCURL4_OPENSSL_DEV_VERSION="${LIBCURL4_OPENSSL_DEV_VERSION:-7.35.0-1ubuntu2.5}"
LIBXSLT1_DEV_VERSION="${LIBXSLT1_DEV_VERSION:-1.1.28-2build1}"
LIBYAML_DEV_VERSION="${LIBYAML_DEV_VERSION:-0.1.4-3ubuntu3.1}"
LIBPQ_DEV_VERSION="${LIBPQ_DEV_VERSION:-9.3.10-0ubuntu0.14.04}"
LIBREADLINE6_DEV_VERSION="${LIBREADLINE6_DEV_VERSION:-6.3-4ubuntu2}"
LIBNCURSES5_DEV_VERSION="${LIBNCURSES5_DEV_VERSION:-5.9+20140118-1ubuntu1}"
LIBEDITLINE_DEV_VERSION="${LIBEDITLINE_DEV_VERSION:-1.12-6}"
LIBEDIT_DEV_VERSION="${LIBEDIT_DEV_VERSION:-3.1-20130712-2}"

#
# Git configuration
#
GIT_VERSION="${GIT_VERSION:-1:1.9.1-1ubuntu0.2}"
GIT_USER="${GIT_USER:-''}"
GIT_EMAIL="${GIT_EMAIL:-''}"

#
# Ruby configuration
#
RUBY_DEV_VERSION="${RUBY_DEV_VERSION:-1:1.9.3.4}"
RVM_RUBY_VERSION="${RVM_RUBY_VERSION:-rbx-2.5.2}"

GEM_BUNDLER_VERSION="${GEM_BUNDLER_VERSION:-1.11.2}"
GEM_CM_DEV="${GEM_CM_DEV:-''}"
GEM_CM_DIRECTORY="${GEM_CM_DIRECTORY:-''}"
GEM_CM_REVISION="${GEM_CM_REVISION:-0.1}"
GEM_CM_VERSION="${GEM_CM_VERSION:-0.1.3}"

#
# Command versions (only for testing purposes)
#
MAKE_CMD_VERSION="${MAKE_CMD_VERSION:-3.81}"
CMAKE_CMD_VERSION="${CMAKE_CMD_VERSION:-2.8.12.2}"
RAKE_CMD_VERSION="${RAKE_CMD_VERSION:-10.4.2}"
RUBY_CMD_VERSION="${RUBY_CMD_VERSION:-2.5.2}"
GEM_CMD_VERSION="${GEM_CMD_VERSION:-2.4.8}"
OPENSSL_CMD_VERSION="${OPENSSL_CMD_VERSION:-1.0.1f}"
UNZIP_CMD_VERSION="${UNZIP_CMD_VERSION:-6.00}"
CURL_CMD_VERSION="${CURL_CMD_VERSION:-7.35.0}"
GIT_CMD_VERSION="${GIT_CMD_VERSION:-1.9.1}"
CM_CMD_VERSION="${CM_CMD_VERSION:-0.1.3}"
