#
# System settings
#
DNS_IP="${DNS_IP:-208.67.222.222}"
SYSTEM_TIMEZONE="${SYSTEM_TIMEZONE:-EST}"
SYSTEM_LOCALE="${SYSTEM_LOCALE:-en_US.UTF-8}"

#
# Git configuration
#
GIT_USER="${GIT_USER:-''}"
GIT_EMAIL="${GIT_EMAIL:-''}"

#
# Ruby configuration
#
RVM_RUBY_VERSION="${RVM_RUBY_VERSION:-rbx-2.5.2}"

GEM_CM_DEV="${GEM_CM_DEV:-''}"
GEM_CM_DIRECTORY="${GEM_CM_DIRECTORY:-''}"
GEM_CM_REVISION="${GEM_CM_REVISION:-0.1}"
GEM_CM_VERSION="${GEM_CM_VERSION:-0.1.3}"
